[calo_electron]
type = 'hist2d'
vars = 'sCal_electron'
xlabel = 'True Deposited Energy [MeV]'
ylabel = 'Reco Calo Energy [MeV]'
title = 'Electron Calo Energy Estimation'

[calo_electron2electron]
type = 'hist2d'
vars = 'sCal_electron2electron'
xlabel = 'True Kinetic Energy [MeV]'
ylabel = 'Reco Calo Energy [MeV]'
title = 'Electron Calo Energy Estimation'

[calo_electron_bias2d]
type = 'hist2d'
vars = 'sCal_electron_bias2d'
xlabel = 'True Kinetic Energy [MeV]'
ylabel = '($E_{calo}$ -  $E_{true}$) / $E_{true}$'
title = 'Electron Calo Energy Estimation'

[calo_electron_bias]
type = 'hist1d'
vars = ['sCal_electron_bias',]
labels = ['electrons',]
xlabel = '($E_{calo}$ -  $E_{true}$) / $E_{true}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Contained Electrons'
plot_kwargs = {histtype = 'barstacked'}

[calo_nonccelectron_bias]
type = 'hist1d'
vars = ['sCal_noncc_electron_bias',]
labels = ['electron',]
xlabel = '($E_{calo}$ -  $E_{true}$) / $E_{true}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Contained Electron'
plot_kwargs = {histtype = 'barstacked'}

[calo_wellrecoelectron_bias]
type = 'hist1d'
vars = ['sCal_wellreco_electron_bias',]
labels = ['electrons',]
xlabel = '($E_{calo}$ -  $E_{true}$) / $E_{true}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Contained Electrons'
plot_kwargs = {histtype = 'barstacked'}

[calo_wellrecoproton_bias]
type = 'hist1d'
vars = ['sCal_wellreco_proton_bias',]
labels = ['protons',]
xlabel = '($E_{csda}$ -  $E_{true}$) / $E_{true}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Contained Protons'
plot_kwargs = {histtype = 'barstacked'}

[cos_open_angle]
type = 'hist1d'
vars = ['sCos_open_angle',]
labels = ['1$e$1p',]
xlabel = 'Cos(theta)
ylabel = 'Entries / 2.6e20 POT'
title = 'Cosine of Opening Angle'
plot_kwargs = {histtype = 'barstacked'}