[energy_1e1p_bias]
type = 'hist1d'
vars = ['sEnergy_1e1p_signal_bias', 'sEnergy_1e1p_othernu_bias']
labels = ['1$e$1p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{visible}$) / $E_{visible}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Selected 1$e$1p Candidates'
plot_kwargs = {histtype = 'barstacked'}

[nuenergy_1e1p_bias]
type = 'hist1d'
vars = ['sNuEnergy_1e1p_signal_bias', 'sNuEnergy_1e1p_othernu_bias']
labels = ['1$e$1p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{\nu}$) / $E_{\nu}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Selected 1$e$1p Candidates'
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_1e1p]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_Topology_All1e1pCut'
categories = {0 = '1$e$1p', 2 = '1$e$Np, N$>$1', 1 = '1$e$0h', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[0,], [1,], [2,], [3,], [4], [5,], [6,] [7,]]
colors = [0, 1, 2, 3, 4, 5, 6, 7]
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_interaction_mode_1e1p]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_InteractionMode_All1e1pCut'
categories = {0 = '$\nu_e$ CC QE', 1 = '$\nu_e$ CC Res', 2 = '$\nu_e$ CC MEC', 3 = '$\nu_e$ CC DIS', 4 = '$\nu_e$ CC Coh', 5 = '$\nu_\mu$ CC', 6 = '$\nu$ NC', 7 = 'Cosmic'}
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_flashtime_1e1p]
type = 'hist1d'
vars = 'sFlashTimePTT_Topology_All1e1pCut'
categories = {0 = '1$e$1p', 2 = '1$e$Np, N$>$1', 1 = '1$e$0h', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[0,], [1,], [2,], [3,], [4], [5,], [6,],[7,]]
colors = [0, 1, 2, 3, 4, 5, 6,7]
xlabel = 'Matched Flash Time [$e$s]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
plot_kwargs = {histtype = 'barstacked'}

[reco_flashtime_all]
type = 'hist1d'
vars = 'sFlashTimePTT_NoCut'
categories = {0 = '1$e$1p', 1 = '1$e$0h', 2 = '1$e$Np, N$>$1', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[0,], [2,], [1,], [3,], [4], [5,], [6,], [7]]
colors = [0, 1, 2, 3, 4, 5, 6, 7]
xlabel = 'Matched Flash Time [$e$s]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Interaction Flash Time'
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_1e1p_ttp]
type = 'hist1d'
vars = 'sVisibleEnergyTTP_Topology_All1e1pCut'
categories = {0 = '1$e$1p', 2 = '1$e$Np, N$>$1', 1 = '1$e$0h', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[0,], [1,], [2,], [3,], [4], [5,], [6,] [7,]]
colors = [0, 1, 2, 3, 4, 5, 6, 7]
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_interaction_mode_1e1p_ttp]
type = 'hist1d'
vars = 'sVisibleEnergyTTP_InteractionMode_All1e1pCut'
categories = {0 = '$\nu_e$ CC QE', 1 = '$\nu_e$ CC Res', 2 = '$\nu_e$ CC MEC', 3 = '$\nu_e$ CC DIS', 4 = '$\nu_e$ CC Coh', 5 = '$\nu_\mu$ CC', 6 = '$\nu$ NC', 7 = 'Cosmic'}
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_flashtime_1e1p_ttp]
type = 'hist1d'
vars = 'sFlashTimeTTP_Topology_All1e1pCut'
categories = {0 = '1$e$1p', 2 = '1$e$Np, N$>$1', 1 = '1$e$0h', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[0,], [1,], [2,], [3,], [4], [5,], [6,],[7,]]
colors = [0, 1, 2, 3, 4, 5, 6,7]
xlabel = 'Matched Flash Time [$e$s]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$1p Candidates'
plot_kwargs = {histtype = 'barstacked'}

