[energy_1eNp_bias]
type = 'hist1d'
vars = ['sEnergy_1eNp_1p_signal_bias', 'sEnergy_1eNp_Np_signal_bias', 'sEnergy_1eNp_othernu_bias']
labels = ['1$e$1p', '1$e$2+p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{visible}$) / $E_{visible}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}

[nuenergy_1eNp_bias]
type = 'hist1d'
vars = ['sNuEnergy_1eNp_1p_signal_bias', 'sNuEnergy_1eNp_Np_signal_bias', 'sNuEnergy_1eNp_othernu_bias']
labels = ['1$e$1p', '1$e$2+p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{\nu}$) / $E_{\nu}$'
ylabel = 'Entries / 2.6e20 POT'
title = 'Energy Reconstruction for Selected 1$e$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_1eNp]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_Topology_All1eNpCut'
categories = {0 = '1$e$1p', 1 = '1$e$0h', 2 = '1$e$Np, N$\geq$1', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[2,0], [1,], [3,], [4], [5,], [6,],[7,]]
colors = [0, 2, 3, 4, 5, 6]
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$Np Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_interaction_mode_1eNp]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_InteractionMode_All1eNpCut'
categories = {0 = '$\nu_e$ CC QE', 1 = '$\nu_e$ CC Res', 2 = '$\nu_e$ CC MEC', 3 = '$\nu_e$ CC DIS', 4 = '$\nu_e$ CC Coh', 5 = '$\nu_e$ CC', 6 = '$\nu$ NC', 7 = 'Cosmic'}
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$Np Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_flashtime_1eNp]
type = 'hist1d'
vars = 'sFlashTimePTT_Topology_All1eNpCut'
categories = {0 = '1$e$1p', 1 = '1$e$0h', 2 = '1$e$Np, N$\geq$1', 3 = '1$e$1$\pi$1p', 4 = 'Other $\nu_e$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Uncontained'}
merge = [[2,0], [1,], [3,], [4], [5,], [6,],[7,]]
colors = [0, 2, 3, 4, 5, 6]
xlabel = 'Matched Flash Time [$e$s]'
ylabel = 'Entries / 2.6e20 POT'
title = 'Selected 1$e$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}