[energy_1muNp_bias]
type = 'hist1d'
vars = ['sEnergy_1muNp_1p_signal_bias', 'sEnergy_1muNp_Np_signal_bias', 'sEnergy_1muNp_othernu_bias']
labels = ['1$\mu$1p', '1$\mu$2+p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{visible}$) / $E_{visible}$'
ylabel = 'Entries / 2.5e20 POT'
title = 'Selected 1$\mu$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}

[nuenergy_1muNp_bias]
type = 'hist1d'
vars = ['sNuEnergy_1muNp_1p_signal_bias', 'sNuEnergy_1muNp_Np_signal_bias', 'sNuEnergy_1muNp_othernu_bias']
labels = ['1$\mu$1p', '1$\mu$2+p', 'Other $\nu$']
xlabel = '($E_{reco}$ -  $E_{\nu}$) / $E_{\nu}$'
ylabel = 'Entries / 2.5e20 POT'
title = 'Energy Reconstruction for Selected 1$\mu$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_1muNp]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_Topology_All1muNpCut'
categories = {0 = '1$\mu$1p', 1 = '1$\mu$0h', 2 = '1$\mu$Np, N$\geq$1', 3 = '1$\mu$1$\pi$1p', 4 = 'Other $\nu_\mu$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Other'}
merge = [[2,0], [1,], [3,], [4,7], [5,], [6,]]
colors = [0, 2, 3, 4, 5, 6]
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.5e20 POT'
title = 'Selected 1$\mu$Np Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_energy_interaction_mode_1muNp]
type = 'hist1d'
vars = 'sVisibleEnergyPTT_InteractionMode_All1muNpCut'
categories = {0 = '$\nu_\mu$ CC QE', 1 = '$\nu_\mu$ CC Res', 2 = '$\nu_\mu$ CC MEC', 3 = '$\nu_\mu$ CC DIS', 4 = '$\nu_\mu$ CC Coh', 5 = '$\nu_e$ CC', 6 = '$\nu$ NC', 7 = 'Cosmic'}
xlabel = 'Reconstructed Visible Energy [MeV]'
ylabel = 'Entries / 2.5e20 POT'
title = 'Selected 1$\mu$Np Candidates'
show_percentage = true
plot_kwargs = {histtype = 'barstacked'}

[reco_flashtime_1muNp]
type = 'hist1d'
vars = 'sFlashTimePTT_Topology_All1muNpCut'
categories = {0 = '1$\mu$1p', 1 = '1$\mu$0h', 2 = '1$\mu$Np, N$\geq$1', 3 = '1$\mu$1$\pi$1p', 4 = 'Other $\nu_\mu$ CC', 5 = '$\nu$ NC', 6 = 'Cosmic', 7 = 'Other'}
merge = [[2,0], [1,], [3,], [4,7], [5,], [6,]]
colors = [0, 2, 3, 4, 5, 6]
xlabel = 'Matched Flash Time [$\mu$s]'
ylabel = 'Entries / 2.5e20 POT'
title = 'Selected 1$\mu$Np Candidates'
plot_kwargs = {histtype = 'barstacked'}